# Generated by Django 4.2.10 on 2026-02-14 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Verified Purchase')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is Approved')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='reviews.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review Helpful Mark',
                'verbose_name_plural': 'Review Helpful Marks',
            },
        ),
    ]
