# Generated by Django 4.2.10 on 2026-02-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='balancetopup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_topups', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['user', '-created_at'], name='payments_ba_user_id_8c5b13_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='payments_ba_transac_f57bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetopup',
            index=models.Index(fields=['user', 'status'], name='payments_ba_user_id_f0456f_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetopup',
            index=models.Index(fields=['payment_id'], name='payments_ba_payment_d42d34_idx'),
        ),
    ]
