# Generated by Django 4.2.10 on 2026-02-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_code', models.TextField(verbose_name='Key/Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Purchased At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Digital Key',
                'verbose_name_plural': 'Digital Keys',
                'ordering': ['is_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalKeyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, verbose_name='Delivered At')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='digital_keys.digitalkey', verbose_name='Digital Key')),
            ],
            options={
                'verbose_name': 'Digital Key Delivery',
                'verbose_name_plural': 'Digital Key Deliveries',
                'ordering': ['-delivered_at'],
            },
        ),
    ]
