# Generated by Django 4.2.10 on 2026-02-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_keys', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkeydelivery',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_key_delivery', to='orders.orderitem', verbose_name='Order Item'),
        ),
    ]
