# Generated by Django 4.2.10 on 2026-02-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('digital_keys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkey',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'digital'}, on_delete=django.db.models.deletion.CASCADE, related_name='digital_keys', to='products.product', verbose_name='Product'),
        ),
    ]
