# Generated by Django 4.2.10 on 2026-02-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital_keys', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkey',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_keys', to=settings.AUTH_USER_MODEL, verbose_name='Purchased By'),
        ),
        migrations.AddIndex(
            model_name='digitalkey',
            index=models.Index(fields=['product', 'is_used'], name='digital_key_product_3159ce_idx'),
        ),
    ]
